### ISSUE TITLE
Test API 出错 KeyError: 'refresh_token'

### ISSUE THREAD

**Issue by jiegto** [InspAlgo/clockwork#3]
你好，我在 Test API 阶段，一直提示 KeyError: 'refresh_token' 错误，导致无法进行。

请问这种情况可以如何处理，可以帮忙看一下吗？谢谢！

![CleanShot 2020-11-06 at 17 46 24](https://user-images.githubusercontent.com/15905889/98351706-07806d00-2058-11eb-9bbf-3d4f32d433dd.jpg)

以下是我的配置
```
GIST_HTTPS_WITH_TOKEN ：https://$token@gist.github.com/$gistID.git
GIST_ID：$gistID
GIST_TEXT：E5_token.txt
CONFIG_ID：id=r'$clientID'
CONFIG_KEY：secret=r'$clientSecret'
```

E5_token.txt 里面已填入通过` sudo rclone authorize "onedrive" "$clientID" "$clientSecret" `获取到的 refresh_token

**Comment by InspAlgo** [comment]
![image](https://user-images.githubusercontent.com/30190529/98506199-ead17880-2295-11eb-86f6-97206739c57c.png)
你的 `CONFIG_ID` 和 `CONFIG_KEY` 赋值写法不对，请直接填入你的 `clientID` 和 `clientSecret` 的值，而不需要写成 `id=r'$clientID'` 和 `secret=r'clientSecret'` 的形式，这里是我的疏忽，没有在 README 中提醒，虽然原项目中是这样写的，但我在 main.py 第 37 与 38 行（如下图）：

![image](https://user-images.githubusercontent.com/30190529/98506630-e5286280-2296-11eb-947d-d61e129d281f.png)
中使用 `os.environ` 直接读取环境变量，所以不需要 `id=r'$clientID'` 和 `secret=r'clientSecret'` 的写法。

你看原项目的 Actions 的 YAML 中是这样处理的：
![image](https://user-images.githubusercontent.com/30190529/98507003-b1017180-2297-11eb-9d85-6d6bc47d926e.png)
想必你已经发现不同了，再次因我的疏忽而致歉，我将在 README 中进行补充。

**Comment by jiegto** [comment]
非常感谢解答，终于成功了。

确实没有注意到两者的差异，惯性思维以为是一样的设定，没有仔细核实，给你添麻烦了。再次感谢！
